# coding: utf-8

"""
    NeuroLinker API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class DocumentStatusResponse(BaseModel):
    """
    Response from get_document_status() endpoint - contains filtered Firestore fields
    """ # noqa: E501
    success: StrictBool = Field(description="Whether the operation was successful")
    document_id: StrictStr = Field(description="Unique identifier for the document")
    request_id: StrictStr = Field(description="Unique identifier for the parent request")
    status: StrictStr = Field(description="Document status: 'pending', 'processing', 'completed', or 'failed'")
    file_name: StrictStr = Field(description="Original filename of the document")
    file_type: StrictStr = Field(description="MIME type of the document")
    file_size_bytes: StrictInt = Field(description="Size of the document in bytes")
    total_pages: Optional[StrictInt] = None
    user_uid: StrictStr = Field(description="User identifier who owns this document")
    started_at: Optional[Any] = Field(default=None, description="Timestamp when processing started")
    completed_at: Optional[Any] = Field(default=None, description="Timestamp when processing completed")
    results: Optional[Dict[str, Any]] = None
    document_page_url: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["success", "document_id", "request_id", "status", "file_name", "file_type", "file_size_bytes", "total_pages", "user_uid", "started_at", "completed_at", "results", "document_page_url"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DocumentStatusResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of started_at
        if self.started_at:
            _dict['started_at'] = self.started_at.to_dict()
        # override the default output from pydantic by calling `to_dict()` of completed_at
        if self.completed_at:
            _dict['completed_at'] = self.completed_at.to_dict()
        # set to None if total_pages (nullable) is None
        # and model_fields_set contains the field
        if self.total_pages is None and "total_pages" in self.model_fields_set:
            _dict['total_pages'] = None

        # set to None if started_at (nullable) is None
        # and model_fields_set contains the field
        if self.started_at is None and "started_at" in self.model_fields_set:
            _dict['started_at'] = None

        # set to None if completed_at (nullable) is None
        # and model_fields_set contains the field
        if self.completed_at is None and "completed_at" in self.model_fields_set:
            _dict['completed_at'] = None

        # set to None if results (nullable) is None
        # and model_fields_set contains the field
        if self.results is None and "results" in self.model_fields_set:
            _dict['results'] = None

        # set to None if document_page_url (nullable) is None
        # and model_fields_set contains the field
        if self.document_page_url is None and "document_page_url" in self.model_fields_set:
            _dict['document_page_url'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DocumentStatusResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "success": obj.get("success"),
            "document_id": obj.get("document_id"),
            "request_id": obj.get("request_id"),
            "status": obj.get("status"),
            "file_name": obj.get("file_name"),
            "file_type": obj.get("file_type"),
            "file_size_bytes": obj.get("file_size_bytes"),
            "total_pages": obj.get("total_pages"),
            "user_uid": obj.get("user_uid"),
            "started_at": AnyOf.from_dict(obj["started_at"]) if obj.get("started_at") is not None else None,
            "completed_at": AnyOf.from_dict(obj["completed_at"]) if obj.get("completed_at") is not None else None,
            "results": obj.get("results"),
            "document_page_url": obj.get("document_page_url")
        })
        return _obj


