# coding: utf-8

"""
    NeuroLinker API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from typing_extensions import Self

class JobPerformance(BaseModel):
    """
    JobPerformance
    """ # noqa: E501
    extraction_time: Union[StrictFloat, StrictInt] = Field(description="Time taken by the extraction pipeline in seconds")
    document_download_time: Union[StrictFloat, StrictInt] = Field(description="Time taken to download documents from storage in seconds")
    document_upload_time: Union[StrictFloat, StrictInt] = Field(description="Time taken to upload documents to storage in seconds")
    total_time: Union[StrictFloat, StrictInt] = Field(description="Total time taken for the job in seconds")
    __properties: ClassVar[List[str]] = ["extraction_time", "document_download_time", "document_upload_time", "total_time"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobPerformance from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobPerformance from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "extraction_time": obj.get("extraction_time"),
            "document_download_time": obj.get("document_download_time"),
            "document_upload_time": obj.get("document_upload_time"),
            "total_time": obj.get("total_time")
        })
        return _obj


